---
- name: create pvc
  k8s:
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: bitcoin
        namespace: "{{ meta.namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi

# tasks file for Bitd
- name: start bitd
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-bitd'
        namespace: '{{ meta.namespace }}'
      spec:
        selector:
          matchLabels:
            app: bitd
        template:
          metadata:
            labels:
              app: bitd
          spec:
            containers:
            - name: bitd
              image: "docker.io/dymurray/bitcoin-sv-bitd"
              ports:
                - containerPort: 8332
              volumeMounts:
                - name: bitcoin
                  mountPath: /root/.bitcoin
            volumes:
              - name: bitcoin
                persistentVolumeClaim:
                  claimName: bitcoin
  register: dep

- name: create service
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: '{{ meta.name }}-bitd'
        namespace: '{{ meta.namespace }}'
      spec:
        type: NodePort
        selector:
          app: bitd
        ports:
        - protocol: TCP
          port: 8332
          targetPort: 8332
          name: rpc
  register: svc

- debug:
    msg: "{{ svc }}"

- debug:
    msg: "{{ svc.result.spec.clusterIP }}:{{ svc.result.spec.ports[0].port }}"

- uri:
    url: http://192.168.42.96:{{svc.result.spec.ports[0].nodePort}}
    method: POST
    user: foobar
    password: foobar
    body: "{{ lookup('file', 'getblockchaininfo.json') }}"
    force_basic_auth: yes
    body_format: json
  register: chaininfo

- uri:
    url: http://192.168.42.96:{{svc.result.spec.ports[0].nodePort}}
    method: POST
    user: foobar
    password: foobar
    body: "{{ lookup('file', 'getwalletinfo.json') }}"
    force_basic_auth: yes
    body_format: json
  register: walletinfo

- uri:
    url: http://192.168.42.96:{{svc.result.spec.ports[0].nodePort}}
    method: POST
    user: foobar
    password: foobar
    body: "{{ lookup('file', 'getaccountaddress.json') }}"
    force_basic_auth: yes
    body_format: json
  register: addressinfo
- debug:
    msg: "{{ addressinfo.json }}"

- k8s_status:
    api_version: bitcoin.example.com/v1
    kind: Bitd
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    status:
      address: "{{ addressinfo.json.result }}"
      blockCount: "{{ chaininfo.json.result.blocks | int }}"
      headers: "{{ chaininfo.json.result.headers | int }}"
      balance: "{{ walletinfo.json.result.balance }}"
      unconfirmedBalance: "{{ walletinfo.json.result.unconfirmed_balance }}"
